services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pipo_os
      POSTGRES_PASSWORD: pipo_os
      POSTGRES_DB: pipo_os
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
