/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface OutboundWebhookDeliveries {
  attempt_count: Generated<number>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  payload: Json;
  signing_secret: string;
  status: Generated<string>;
  status_history_id: string;
  target_url: string;
  ticket_id: string;
  webhook_config_id: string;
}

export interface TicketComments {
  author_id: string | null;
  body: string;
  channel: Generated<string>;
  created_at: Generated<Timestamp>;
  event_type: string | null;
  id: Generated<string>;
  kind: string;
  metadata: Generated<Json>;
  ticket_id: string;
  visibility: string;
}

export interface TicketEmailAttachments {
  filename: string;
  id: Generated<string>;
  mime_type: string;
  size_bytes: Int8;
  storage_url: string;
  ticket_email_id: string;
}

export interface TicketEmails {
  body_html: string | null;
  body_text: string | null;
  cc_addresses: Generated<Json>;
  comment_id: string;
  created_at: Generated<Timestamp>;
  direction: string;
  from_address: string;
  gmail_message_id: string;
  gmail_thread_id: string;
  has_attachments: Generated<boolean>;
  id: Generated<string>;
  snippet: string | null;
  subject: string | null;
  ticket_id: string;
  to_addresses: Generated<Json>;
}

export interface TicketFormValues {
  field_key: string;
  field_value: Json;
  id: Generated<string>;
  ticket_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface TicketGroupCompanies {
  /**
   * No foreign key, and none is possible: companies live in another service, so there is no table to reference. Being a uuid is all the database guarantees — never that it names a company. Validation belongs to the edge that writes it (PD-051).
   */
  company_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
}

export interface TicketGroupMemberCompanies {
  company_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
  user_id: string;
}

export interface TicketGroupMembers {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  group_id: string;
  role: Generated<string>;
  user_id: string;
}

export interface TicketGroups {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  name: string;
  /**
   * Cycles are refused by the ticket_groups_no_cycle trigger. A single root is NOT enforced: a unique partial index on parent_id IS NULL cannot coexist with the parentless groups POST /api/groups creates. PD-050 decides whether the API refuses a second root.
   */
  parent_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface TicketQueues {
  created_at: Generated<Timestamp>;
  created_by: string;
  filters: Generated<Json>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface TicketQueuesXGroup {
  created_at: Generated<Timestamp>;
  group_id: string;
  queue_id: string;
}

export interface Tickets {
  action_date: Timestamp | null;
  assignee_id: string | null;
  closed_at: Timestamp | null;
  collaborators: Generated<Json>;
  company_id: string;
  created_at: Generated<Timestamp>;
  display_number: Generated<string>;
  enrollment_id: string;
  enrollment_snapshot: Generated<Json>;
  enrollment_type: string;
  force_completion: Generated<boolean>;
  group_id: string | null;
  id: Generated<string>;
  parent_ticket_id: string | null;
  pending_documentation: Generated<string[]>;
  priority: string | null;
  queue_id: string | null;
  requester: Json | null;
  source_system: string;
  status: string;
  tags: Generated<string[]>;
  title: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TicketStatusHistory {
  author_id: string | null;
  author_type: string;
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: Generated<string>;
  reason: string | null;
  ticket_id: string;
  to_status: string;
}

export interface WebhookConfigs {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  event_types: Generated<Json>;
  id: Generated<string>;
  name: string;
  secret: string;
  target_url: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  outbound_webhook_deliveries: OutboundWebhookDeliveries;
  ticket_comments: TicketComments;
  ticket_email_attachments: TicketEmailAttachments;
  ticket_emails: TicketEmails;
  ticket_form_values: TicketFormValues;
  ticket_group_companies: TicketGroupCompanies;
  ticket_group_member_companies: TicketGroupMemberCompanies;
  ticket_group_members: TicketGroupMembers;
  ticket_groups: TicketGroups;
  ticket_queues: TicketQueues;
  ticket_queues_x_group: TicketQueuesXGroup;
  ticket_status_history: TicketStatusHistory;
  tickets: Tickets;
  webhook_configs: WebhookConfigs;
}
