/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthDeskRouteImport } from './routes/_auth/_desk'
import { Route as AuthDeskIndexRouteImport } from './routes/_auth/_desk/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeskRoute = AuthDeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeskIndexRoute = AuthDeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDeskRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthDeskIndexRoute
  '/login/': typeof PublicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthDeskIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/_desk': typeof AuthDeskRouteWithChildren
  '/_auth/_desk/': typeof AuthDeskIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/_desk'
    | '/_auth/_desk/'
    | '/_public/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_desk': {
      id: '/_auth/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthDeskRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_desk/': {
      id: '/_auth/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthDeskIndexRouteImport
      parentRoute: typeof AuthDeskRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthDeskRouteChildren {
  AuthDeskIndexRoute: typeof AuthDeskIndexRoute
}

const AuthDeskRouteChildren: AuthDeskRouteChildren = {
  AuthDeskIndexRoute: AuthDeskIndexRoute,
}

const AuthDeskRouteWithChildren = AuthDeskRoute._addFileChildren(
  AuthDeskRouteChildren,
)

interface AuthRouteChildren {
  AuthDeskRoute: typeof AuthDeskRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDeskRoute: AuthDeskRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
