apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipo-os
  namespace: default
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pipo-os.piposaude.com.br
  rules:
    - host: pipo-os.piposaude.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pipo-os
                port:
                  number: 80
